id: I3F254F86
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W3CN1669
  ocr_info:
    timestamp: 03/21/23T14:11:22
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-02-28 22:34:51.591372+00:00
last_modified: 2024-02-28 22:34:51.591378+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN1669
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN1669
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དག་ཡིག་ལི་ཤིའི་གུར་ཁང་།
  languages:
  - bo
  author: ཀརྨ་ལོ་ཙཱ་བ་རིན་ཆེན་བཀྲ་ཤིས།
statistics:
  ocr_word_mean_confidence_index: 0.967605633802817
  ocr_word_median_confidence_index: 0.99
bases:
  I3CN1671:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN1671
      total_pages: 30
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN1671.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.967605633802817
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
